defaults:
  - dataset: cifar10
is_load_bag: True

lr: 0.0001
batch_size: 512
num_workers: 2
device: 'cuda'
num_epochs: 30
is_pretrained: True

fpl:
  is_online_prediction: True
  sigma: 1
  eta: 1
  loss_f: song